language: c

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install build-essential > /dev/null
    - sudo apt-get install nodejs > /dev/null
    - sudo apt-get install mono-devel > /dev/null
    - npm install
    - npm install -g --dev

script:
    - make test
    - make install
    - make test-compile


notifications:
    email: false


