language: c

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install build-essential
    - sudo apt-get install nodejs
    - sudo apt-get install mono-complete

script:
    - make test
    - make test-compile
    - make install

notifications:
    email: false


