language: node_js

node_js:
    - node

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install build-essential
    - sudo apt-get install mono-devel mono-mcs
    - sudo apt-get install libreadline-dev
    - npm install
    - npm install --dev

script:
    - make test
    - make install
    - make test-compile


notifications:
    email: false


